// Simulated server JSON data (in real project load via fetch('data.json'))
const MENU_DATA = {
  categories: [
    {
      id: "salads",
      name: "🥗 Salads",
      description: "Fresh, crisp, and nutrient-packed salads for every taste.",
      image: "🥗",
      items: [
        {
          id: "s1",
          name: "Green Garden Salad",
          description:
            "Mixed greens, cherry tomatoes, cucumber, olive oil dressing. Light and refreshing.",
          image: "images/green-garden-salad.jpg",
          calories: 185,
          protein: "6g",
          fat: "9g",
          price: "$8.99",
          tags: ["vegan", "gluten-free"],
        },
        {
          id: "s2",
          name: "Caesar Salad",
          description:
            "Romaine lettuce, parmesan, croutons, classic Caesar dressing.",
          image: "images/caesar-salad.jpg",
          calories: 310,
          protein: "30g",
          fat: "18g",
          price: "$10.99",
          tags: ["high-protein"],
        },
        {
          id: "s3",
          name: "Greek Salad",
          description:
            "Tomatoes, olives, feta cheese, red onion, oregano, olive oil.",
          image: "images/greek-salad.jpg",
          calories: 220,
          protein: "8g",
          fat: "14g",
          price: "$9.99",
          tags: ["vegetarian", "gluten-free"],
        },
        {
          id: "s4",
          name: "Spinach & Strawberry",
          description:
            "Baby spinach, fresh strawberries, walnuts, balsamic vinaigrette.",
          image: "images/spinach-strawberry.jpg",
          calories: 195,
          protein: "5g",
          fat: "10g",
          price: "$9.49",
          tags: ["vegan", "gluten-free"],
        },
      ],
    },
    {
      id: "bowls",
      name: "🍚 Power Bowls",
      description: "Balanced grain bowls loaded with superfoods.",
      image: "🍚",
      items: [
        {
          id: "b1",
          name: "Quinoa Power Bowl",
          description:
            "Quinoa, roasted sweet potato, chickpeas, tahini dressing, pomegranate.",
          image: "images/quinoa-power-bowl.jpg",
          calories: 420,
          protein: "18g",
          fat: "12g",
          price: "$12.99",
          tags: ["vegan", "high-protein"],
        },
        {
          id: "b2",
          name: "Brown Rice Buddha Bowl",
          description:
            "Brown rice, edamame, shredded carrots, avocado, miso dressing.",
          image: "images/rice-bowl.jpg",
          calories: 390,
          protein: "15g",
          fat: "14g",
          price: "$11.99",
          tags: ["vegan"],
        },
        {
          id: "b3",
          name: "Farro & Roasted Veggie Bowl",
          description:
            "Farro grain, roasted bell peppers, zucchini, cherry tomatoes, pesto.",
          image: "images/farro-veggie-bowl.jpg",
          calories: 360,
          protein: "13g",
          fat: "11g",
          price: "$11.49",
          tags: ["vegetarian"],
        },
        {
          id: "b4",
          name: "Acai Energy Bowl",
          description:
            "Acai base, banana, granola, blueberries, honey drizzle.",
          image: "images/acai-energy-bowl.jpg",
          calories: 340,
          protein: "9g",
          fat: "8g",
          price: "$10.99",
          tags: ["vegan"],
        },
      ],
    },
    {
      id: "proteins",
      name: "🍗 Protein Plates",
      description: "High-protein mains for active lifestyles.",
      image: "🍗",
      items: [
        {
          id: "p1",
          name: "Grilled Chicken & Greens",
          description:
            "Herb-marinated chicken breast, steamed broccoli, quinoa, lemon sauce.",
          image: "images/grilled-chicken-greens.jpg",
          calories: 480,
          protein: "42g",
          fat: "14g",
          price: "$14.99",
          tags: ["high-protein", "gluten-free"],
        },
        {
          id: "p2",
          name: "Salmon & Asparagus",
          description:
            "Atlantic salmon fillet, roasted asparagus, brown rice, dill butter.",
          image: "images/salmon-asparagus.jpg",
          calories: 520,
          protein: "38g",
          fat: "22g",
          price: "$16.99",
          tags: ["high-protein", "omega-3"],
        },
        {
          id: "p3",
          name: "Turkey & Veggie Stir-Fry",
          description:
            "Ground turkey, mixed vegetables, ginger-soy sauce, brown rice.",
          image: "images/turkey-veggie.jpg",
          calories: 440,
          protein: "35g",
          fat: "12g",
          price: "$13.99",
          tags: ["high-protein"],
        },
        {
          id: "p4",
          name: "Lentil & Egg Plate",
          description:
            "Spiced lentils, poached eggs, wilted spinach, whole-grain toast.",
          image: "images/lentil-egg.jpg",
          calories: 410,
          protein: "28g",
          fat: "10g",
          price: "$11.99",
          tags: ["vegetarian", "high-protein"],
        },
      ],
    },
    {
      id: "soups",
      name: "🍲 Soups & Stews",
      description: "Warming, nourishing soups for body and soul.",
      image: "🍲",
      items: [
        {
          id: "so1",
          name: "Lentil Detox Soup",
          description:
            "Red lentils, turmeric, ginger, coconut milk, coriander.",
          image: "images/lentil-soup.jpg",
          calories: 280,
          protein: "16g",
          fat: "8g",
          price: "$9.99",
          tags: ["vegan", "gluten-free"],
        },
        {
          id: "so2",
          name: "Miso Ramen Bowl",
          description:
            "Miso broth, ramen noodles, soft egg, mushrooms, nori, scallions.",
          image: "images/miso-ramen.jpg",
          calories: 350,
          protein: "18g",
          fat: "9g",
          price: "$12.49",
          tags: ["vegetarian"],
        },
        {
          id: "so3",
          name: "Pumpkin Cream Soup",
          description:
            "Roasted pumpkin, cream, nutmeg, pumpkin seeds, croutons.",
          image: "images/cream-soup.jpg",
          calories: 240,
          protein: "6g",
          fat: "10g",
          price: "$8.99",
          tags: ["vegetarian", "gluten-free"],
        },
        {
          id: "so4",
          name: "Chicken & Vegetable Stew",
          description:
            "Free-range chicken, root vegetables, herbs, rich broth.",
          image: "images/chicken-stew.jpg",
          calories: 380,
          protein: "30g",
          fat: "10g",
          price: "$13.49",
          tags: ["gluten-free", "high-protein"],
        },
      ],
    },
    {
      id: "smoothies",
      name: "🥤 Smoothies",
      description: "Cold-pressed smoothies and health drinks.",
      image: "🥤",
      items: [
        {
          id: "sm1",
          name: "Green Detox Smoothie",
          description:
            "Spinach, cucumber, green apple, lemon, ginger, coconut water.",
          image: "images/green-smoothie.jpg",
          calories: 140,
          protein: "4g",
          fat: "1g",
          price: "$7.99",
          tags: ["vegan", "detox"],
        },
        {
          id: "sm2",
          name: "Berry Blast",
          description:
            "Mixed berries, banana, oat milk, chia seeds, maple syrup.",
          image: "images/berry-blast.jpg",
          calories: 210,
          protein: "6g",
          fat: "3g",
          price: "$8.49",
          tags: ["vegan"],
        },
        {
          id: "sm3",
          name: "Tropical Sunrise",
          description:
            "Mango, pineapple, passion fruit, coconut milk, turmeric.",
          image: "images/tropical-sunrise.jpg",
          calories: 190,
          protein: "3g",
          fat: "4g",
          price: "$8.49",
          tags: ["vegan"],
        },
        {
          id: "sm4",
          name: "Protein Peanut Shake",
          description:
            "Banana, peanut butter, oat milk, vanilla protein powder, cacao.",
          image: "images/peanut-shake.jpg",
          calories: 320,
          protein: "22g",
          fat: "10g",
          price: "$9.99",
          tags: ["high-protein", "vegetarian"],
        },
      ],
    },
    {
      id: "desserts",
      name: "🍮 Healthy Desserts",
      description: "Guilt-free sweet treats made with natural ingredients.",
      image: "🍮",
      items: [
        {
          id: "d1",
          name: "Chia Pudding",
          description:
            "Chia seeds in almond milk, topped with fresh mango and coconut flakes.",
          image: "images/chia-pudding.jpg",
          calories: 220,
          protein: "7g",
          fat: "9g",
          price: "$6.99",
          tags: ["vegan", "gluten-free"],
        },
        {
          id: "d2",
          name: "Avocado Chocolate Mousse",
          description:
            "Ripe avocado, raw cacao, maple syrup, vanilla — silky and rich.",
          image: "images/avocado-mousse.jpg",
          calories: 280,
          protein: "4g",
          fat: "18g",
          price: "$7.49",
          tags: ["vegan", "gluten-free"],
        },
        {
          id: "d3",
          name: "Banana Nice Cream",
          description: "Frozen banana blended with almond butter and cinnamon.",
          image: "images/banana-nice-cream.jpg",
          calories: 195,
          protein: "4g",
          fat: "6g",
          price: "$5.99",
          tags: ["vegan", "gluten-free"],
        },
        {
          id: "d4",
          name: "Oat Energy Balls",
          description:
            "Rolled oats, dates, dark chocolate chips, coconut, hemp seeds.",
          image: "images/energy-balls.jpg",
          calories: 160,
          protein: "5g",
          fat: "7g",
          price: "$5.49",
          tags: ["vegan", "snack"],
        },
      ],
    },
  ],
};
